language: cpp
sudo: required
dist: precise

compiler:
    - gcc
    - clang

env:
    - FEATURE=release
    - FEATURE=debug
    - BOOST=62

install:
    - wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
    - echo "deb http://apt.llvm.org/precise/ llvm-toolchain-precise-4.0 main" > clang.list
    - sudo mv clang.list /etc/apt/sources.list.d/
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -qq
    - sudo apt-get install -qq -y libboost-all-dev g++-6 clang-4.0 lldb-4.0 lld-4.0
    - echo "using gcc : 6 : g++-6 ;" >> ~/user-config.jam
    - echo "using clang : 4 : clang++-4.0 ;" >> ~/user-config.jam
    - git clone https://github.com/KayEss/fost-boost.git Boost
    - ./Boost/build ${BOOST} > /dev/null

script:
    - bjam toolset=$CC -q test $FEATURE include=Boost/boost/include/boost-1_${BOOST}
