language: cpp

compiler:
    - gcc
    - clang

env:
    - FEATURE=release
    - FEATURE=debug

install:
    - wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;
    - sudo apt-get update -qq
    - sudo apt-get dist-upgrade -y
    - sudo apt-get install libboost-all-dev

script:
    - bjam toolset=$CC -q test $FEATURE
