language: cpp
sudo: required
dist: xenial

compiler:
    - gcc
    - clang

env:
    - CMAKE_BUILD_TYPE=Debug
    - CMAKE_BUILD_TYPE=Release

cache:
  directories:
    boost-cache

script:
    - mkdir build.tmp && cd build.tmp
    - git clone https://github.com/KayEss/fost-boost.git
    - ln -s ../../boost-cache fost-boost/boost
    - cp ../.travis.CMakeLists.txt CMakeLists.txt
    - cmake . -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE
    - make VERBOSE=1
    - make VERBOSE=1 check


matrix:
    allow_failures:
        - compiler: clang
