language: cpp

compiler:
    - gcc
    - clang

env:
    - FEATURE=release
    - FEATURE=debug

install:
    - wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
    - echo "http://apt.llvm.org/trusty/ llvm-toolchain-trusty main" > /etc/apt/source.list.d/clang.list
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;
    - sudo apt-get update -qq
    - sudo apt-get install -y libboost-all-dev gcc-6 clang-4
    - 'if [ "$CXX" = "g++" ]; then echo "using gcc : 6 : g++-6 ;" > ~/user-config.jam; fi'
    - 'if [ "$CXX" = "clang++" ]; then echo "using clang : 4 : clang++-4.0 ;" > ~/user-config.jam; fi'

script:
    - bjam toolset=$CC -q test $FEATURE
