language: cpp

git:
  submodules: false

compiler:
    - gcc
    - clang

before_install:
    - sed -i 's/git@github.com:/git:\/\/github.com\//' .gitmodules
    - git submodule init
    - git submodule sync --recursive
    - git submodule update --init --recursive

install:
    - sudo apt-get install libboost-all-dev

script:
    - ./build toolset=$CC -q
