language: cpp

compiler:
    - gcc
    - clang

env:
    - FEATURE=release
    - FEATURE=debug

install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;
    - sudo apt-get update -qq
    - sudo apt-get install libboost-all-dev g++-6

script:
    - bjam toolset=$CC -q test $FEATURE
