language: cpp

compiler:
    - gcc-6
    - clang-4

env:
    - FEATURE=release
    - FEATURE=debug

install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;
    - sudo apt-get update -qq
    - sudo apt-get install libboost-all-dev gcc-6 gcc-7

script:
    - bjam toolset=$CC -q test $FEATURE
