version: 2.1

executors:
  clang:
    docker:
    - image: fost/circleci
    environment:
      CC: clang
      CXX: clang++
  gcc:
    docker:
    - image: fost/circleci
    environment:
      CC: gcc-10
      CXX: g++-10

jobs:
  build:
    parameters:
      compiler:
        type: executor
      variant:
        type: string
    executor: << parameters.compiler >>
    steps:
      - checkout
      - run:
          name: libraries
          command: |
            git clone git@github.com:hotkit/fost-boost.git .circleci/boost
            ln -s /opt/fost-boost/boost .circleci/boost/boost
            git clone git@github.com:hotkit/threading.git .circleci/threading
      - run:
          name: cmake
          command: cmake -G Ninja -S .circleci -B .circleci -DCMAKE_BUILD_TYPE=<< parameters.variant >>
      - run:
          name: ninja
          command: ninja -j1 -C .circleci
      - run:
          name: check tests
          command: ninja -j1 -C .circleci check

workflows:
  all-tests:
    jobs:
      - build:
          matrix:
            parameters:
              compiler: [gcc, clang]
              variant: [Debug, Release]
